In [24]:
from tensorflow.keras.preprocessing.text import one_hot


In [25]:
## Sentences
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
    
]

In [26]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [27]:
#Defining Vocabulary size
voc_size=10000


In [28]:
# One hot representation

one_hot_rep=[one_hot(words,voc_size)for words in sent] #what???
one_hot_rep

[[3515, 4356, 9680, 5409],
 [3515, 4356, 9680, 9203],
 [3515, 3740, 9680, 6437],
 [3601, 4154, 5473, 4778, 795],
 [3601, 4154, 5473, 4778, 9749],
 [8649, 3515, 4777, 9680, 3918],
 [3017, 8301, 5201, 4778]]

In [29]:
## Word Embedding Representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

import numpy as np


In [30]:
sent_length=8
embedded_doc=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_doc)
 

[[   0    0    0    0 3515 4356 9680 5409]
 [   0    0    0    0 3515 4356 9680 9203]
 [   0    0    0    0 3515 3740 9680 6437]
 [   0    0    0 3601 4154 5473 4778  795]
 [   0    0    0 3601 4154 5473 4778 9749]
 [   0    0    0 8649 3515 4777 9680 3918]
 [   0    0    0    0 3017 8301 5201 4778]]


In [31]:
#feature dimension
dim=10 #???

In [32]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [33]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [39]:
model.predict(embedded_doc[0])#for every word in a sentence, it will give a vector of 10 dimensions


1/1 [==============================] - 0s 62ms/step


array([[ 0.00974002,  0.02481148, -0.02529688,  0.04463092,  0.01725103,
         0.02291066,  0.04925584,  0.01331973,  0.00958618, -0.02519957],
       [ 0.00974002,  0.02481148, -0.02529688,  0.04463092,  0.01725103,
         0.02291066,  0.04925584,  0.01331973,  0.00958618, -0.02519957],
       [ 0.00974002,  0.02481148, -0.02529688,  0.04463092,  0.01725103,
         0.02291066,  0.04925584,  0.01331973,  0.00958618, -0.02519957],
       [ 0.00974002,  0.02481148, -0.02529688,  0.04463092,  0.01725103,
         0.02291066,  0.04925584,  0.01331973,  0.00958618, -0.02519957],
       [-0.0228557 ,  0.01502744, -0.03740867, -0.02331376,  0.0460078 ,
         0.03398254, -0.01359261, -0.04299036,  0.02315238,  0.04927168],
       [-0.02423304,  0.0385326 ,  0.03695765,  0.04164152,  0.00688026,
         0.0167987 ,  0.01489921, -0.02767155, -0.04683646, -0.03112602],
       [-0.04157708,  0.04088378,  0.02361384, -0.02626537,  0.00679672,
         0.02349425,  0.0322522 , -0.01523806

In [38]:
embedded_doc[0]

array([   0,    0,    0,    0, 3515, 4356, 9680, 5409])